name: Ejecutar script al hacer push

on:
  push:
    branches:
      - '*'

jobs:
  display-info:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar informaci贸n del runner
        run: |
          echo "Informaci贸n del runner:"
          echo "Sistema operativo: ${{ runner.os }}"
          echo "Nombre del runner: ${{ runner.name }}"
          echo "Versi贸n de GitHub Actions: ${{ github.actions }}"
      
      - name: Mostrar informaci贸n de la rama
        run: |
          echo "Rama actual: ${{ github.ref }}"
          echo "Nombre del repositorio: ${{ github.repository }}"